engines:
  credo:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
    exclude_paths:
      - assets/*config.js
  csslint:
    enabled: false
  scss-lint:
    enabled: true
  remark-lint:
    enabled: true
exclude_paths:
- config
- priv
- assets/vendor
- test
- spec
